[2025-01-14T19:04:03.008-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-14T19:04:03.020-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2025-01-15T00:03:39.175529+00:00 [queued]>
[2025-01-14T19:04:03.027-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2025-01-15T00:03:39.175529+00:00 [queued]>
[2025-01-14T19:04:03.028-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-01-14T19:04:03.038-0500] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): inaccurate> on 2025-01-15 00:03:39.175529+00:00
[2025-01-14T19:04:03.044-0500] {standard_task_runner.py:72} INFO - Started process 78883 to run task
[2025-01-14T19:04:03.052-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2025-01-15T00:03:39.175529+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/tutorial_taskflow_api.py', '--cfg-path', '/var/folders/ll/2bfcn_d54ks002mx2dw82c2m0000gn/T/tmp5phnr59_']
[2025-01-14T19:04:03.055-0500] {standard_task_runner.py:105} INFO - Job 92: Subtask inaccurate
[2025-01-14T19:04:03.101-0500] {task_command.py:467} INFO - Running <TaskInstance: my_dag.inaccurate manual__2025-01-15T00:03:39.175529+00:00 [running]> on host macbook-pro-2.local
[2025-01-14T19:04:03.163-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2025-01-15T00:03:39.175529+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-15T00:03:39.175529+00:00'
[2025-01-14T19:04:03.165-0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-14T19:04:03.166-0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-14T19:04:03.166-0500] {logging_mixin.py:190} INFO - Current task name:inaccurate state:running start_date:2025-01-15 00:04:03.021239+00:00
[2025-01-14T19:04:03.167-0500] {logging_mixin.py:190} INFO - Dag name:my_dag and current dag run status:running
[2025-01-14T19:04:03.168-0500] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-14T19:04:03.169-0500] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/ll/2bfcn_d54ks002mx2dw82c2m0000gn/T
[2025-01-14T19:04:03.170-0500] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2025-01-14T19:04:03.178-0500] {subprocess.py:99} INFO - Output:
[2025-01-14T19:04:03.182-0500] {subprocess.py:106} INFO - inaccurate
[2025-01-14T19:04:03.183-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-14T19:04:03.201-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-14T19:04:03.202-0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, run_id=manual__2025-01-15T00:03:39.175529+00:00, execution_date=20250115T000339, start_date=20250115T000403, end_date=20250115T000403
[2025-01-14T19:04:03.210-0500] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-14T19:04:03.211-0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-14T19:04:03.212-0500] {logging_mixin.py:190} INFO - Dag name:my_dag queued_at:2025-01-15 00:03:39.186758+00:00
[2025-01-14T19:04:03.213-0500] {logging_mixin.py:190} INFO - Task hostname:macbook-pro-2.local operator:BashOperator
[2025-01-14T19:04:03.224-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-14T19:04:03.240-0500] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-14T19:04:03.241-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
