[2025-01-13T19:06:55.993-0500] {processor.py:186} INFO - Started process (PID=48851) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T19:06:55.995-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-13T19:06:55.996-0500] {logging_mixin.py:190} INFO - [2025-01-13T19:06:55.996-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T19:06:56.026-0500] {logging_mixin.py:190} INFO - [2025-01-13T19:06:56.025-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-13T19:06:56.026-0500] {logging_mixin.py:190} INFO - [2025-01-13T19:06:56.026-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-13T19:06:56.026-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T19:06:56.172-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.183 seconds
[2025-01-13T19:09:31.820-0500] {processor.py:186} INFO - Started process (PID=50718) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T19:09:31.821-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-13T19:09:31.822-0500] {logging_mixin.py:190} INFO - [2025-01-13T19:09:31.822-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T19:09:31.852-0500] {logging_mixin.py:190} INFO - [2025-01-13T19:09:31.852-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-13T19:09:31.853-0500] {logging_mixin.py:190} INFO - [2025-01-13T19:09:31.852-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-13T19:09:31.853-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T19:09:31.993-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.177 seconds
[2025-01-13T20:01:05.228-0500] {processor.py:186} INFO - Started process (PID=55295) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T20:01:05.230-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-13T20:01:05.231-0500] {logging_mixin.py:190} INFO - [2025-01-13T20:01:05.231-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T20:01:05.265-0500] {logging_mixin.py:190} INFO - [2025-01-13T20:01:05.264-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-13T20:01:05.265-0500] {logging_mixin.py:190} INFO - [2025-01-13T20:01:05.265-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-13T20:01:05.266-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-13T20:01:05.413-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.189 seconds
[2025-01-14T15:55:29.982-0500] {processor.py:186} INFO - Started process (PID=62532) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T15:55:29.985-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T15:55:29.986-0500] {logging_mixin.py:190} INFO - [2025-01-14T15:55:29.986-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T15:55:30.023-0500] {logging_mixin.py:190} INFO - [2025-01-14T15:55:30.023-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T15:55:30.024-0500] {logging_mixin.py:190} INFO - [2025-01-14T15:55:30.024-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T15:55:30.024-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T15:55:30.187-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.210 seconds
[2025-01-14T15:58:38.649-0500] {processor.py:186} INFO - Started process (PID=64811) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T15:58:38.652-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T15:58:38.653-0500] {logging_mixin.py:190} INFO - [2025-01-14T15:58:38.653-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T15:58:38.690-0500] {logging_mixin.py:190} INFO - [2025-01-14T15:58:38.689-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T15:58:38.690-0500] {logging_mixin.py:190} INFO - [2025-01-14T15:58:38.690-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T15:58:38.690-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T15:58:38.847-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.202 seconds
[2025-01-14T16:01:14.924-0500] {processor.py:186} INFO - Started process (PID=66672) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:01:14.926-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:01:14.927-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:01:14.927-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:01:14.961-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:01:14.961-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:01:14.962-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:01:14.961-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:01:14.962-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:01:15.115-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.196 seconds
[2025-01-14T16:03:38.491-0500] {processor.py:186} INFO - Started process (PID=68412) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:03:38.492-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:03:38.494-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:03:38.493-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:03:38.535-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:03:38.535-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:03:38.536-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:03:38.536-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:03:38.536-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:03:38.705-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.220 seconds
[2025-01-14T16:06:03.585-0500] {processor.py:186} INFO - Started process (PID=70221) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:06:03.587-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:06:03.588-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:06:03.588-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:06:03.625-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:06:03.624-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:06:03.625-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:06:03.625-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:06:03.625-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:06:03.784-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.203 seconds
[2025-01-14T16:08:22.894-0500] {processor.py:186} INFO - Started process (PID=71861) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:08:22.896-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:08:22.897-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:08:22.897-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:08:22.929-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:08:22.929-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:08:22.930-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:08:22.930-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:08:22.930-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:08:23.077-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.187 seconds
[2025-01-14T16:11:23.140-0500] {processor.py:186} INFO - Started process (PID=73428) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:11:23.142-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:11:23.143-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:11:23.143-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:11:23.177-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:11:23.176-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:11:23.177-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:11:23.177-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:11:23.177-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:11:23.324-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.188 seconds
[2025-01-14T16:13:39.248-0500] {processor.py:186} INFO - Started process (PID=74951) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:13:39.250-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:13:39.252-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:13:39.252-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:13:39.286-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:13:39.285-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:13:39.286-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:13:39.286-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:13:39.286-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:13:39.443-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.199 seconds
[2025-01-14T16:18:14.408-0500] {processor.py:186} INFO - Started process (PID=78142) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:18:14.410-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:18:14.411-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:18:14.411-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:18:14.445-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:18:14.444-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:18:14.445-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:18:14.445-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:18:14.445-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:18:14.602-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.198 seconds
[2025-01-14T16:20:36.996-0500] {processor.py:186} INFO - Started process (PID=79785) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:20:36.997-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:20:36.999-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:20:36.998-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:20:37.042-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:20:37.042-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:20:37.043-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:20:37.043-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:20:37.043-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:20:37.214-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.222 seconds
[2025-01-14T16:22:51.687-0500] {processor.py:186} INFO - Started process (PID=81298) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:22:51.688-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:22:51.690-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:22:51.689-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:22:51.722-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:22:51.722-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:22:51.722-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:22:51.722-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:22:51.723-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:22:51.878-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.196 seconds
[2025-01-14T16:27:16.397-0500] {processor.py:186} INFO - Started process (PID=84330) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:27:16.399-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:27:16.400-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:27:16.400-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:27:16.437-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:27:16.437-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:27:16.437-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:27:16.437-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:27:16.438-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:27:16.591-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.198 seconds
[2025-01-14T16:29:39.854-0500] {processor.py:186} INFO - Started process (PID=85991) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:29:39.856-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:29:39.857-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:29:39.857-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:29:39.895-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:29:39.895-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:29:39.896-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:29:39.896-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:29:39.896-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:29:40.061-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.212 seconds
[2025-01-14T16:32:06.611-0500] {processor.py:186} INFO - Started process (PID=87634) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:32:06.613-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:32:06.614-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:32:06.614-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:32:06.651-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:32:06.650-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:32:06.651-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:32:06.651-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:32:06.651-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:32:06.814-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.208 seconds
[2025-01-14T16:34:28.260-0500] {processor.py:186} INFO - Started process (PID=89257) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:34:28.262-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:34:28.263-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:34:28.263-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:34:28.300-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:34:28.300-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:34:28.301-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:34:28.301-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:34:28.301-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:34:28.453-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.198 seconds
[2025-01-14T16:37:29.337-0500] {processor.py:186} INFO - Started process (PID=91219) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:37:29.340-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:37:29.342-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:37:29.341-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:37:29.399-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:37:29.399-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:37:29.400-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:37:29.400-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:37:29.400-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:37:29.634-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.303 seconds
[2025-01-14T16:40:16.605-0500] {processor.py:186} INFO - Started process (PID=93084) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:40:16.606-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:40:16.607-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:40:16.607-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:40:16.643-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:40:16.642-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:40:16.643-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:40:16.643-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:40:16.643-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:40:16.804-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.204 seconds
[2025-01-14T16:42:46.387-0500] {processor.py:186} INFO - Started process (PID=94874) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:42:46.388-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:42:46.389-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:42:46.389-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:42:46.422-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:42:46.422-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:42:46.423-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:42:46.422-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:42:46.423-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:42:46.573-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.191 seconds
[2025-01-14T16:47:25.388-0500] {processor.py:186} INFO - Started process (PID=98032) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:47:25.389-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:47:25.390-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:47:25.390-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:47:25.424-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:47:25.423-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:47:25.424-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:47:25.424-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:47:25.424-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:47:25.575-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.191 seconds
[2025-01-14T16:49:49.181-0500] {processor.py:186} INFO - Started process (PID=99678) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:49:49.182-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:49:49.184-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:49:49.183-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:49:49.223-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:49:49.223-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:49:49.224-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:49:49.224-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:49:49.224-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:49:49.398-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.222 seconds
[2025-01-14T16:52:20.217-0500] {processor.py:186} INFO - Started process (PID=2091) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:52:20.219-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:52:20.221-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:52:20.220-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:52:20.258-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:52:20.258-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:52:20.258-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:52:20.258-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:52:20.259-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:52:20.429-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.216 seconds
[2025-01-14T16:54:47.515-0500] {processor.py:186} INFO - Started process (PID=3762) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:54:47.516-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:54:47.518-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:54:47.517-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:54:47.554-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:54:47.553-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:54:47.554-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:54:47.554-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:54:47.554-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:54:47.710-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.199 seconds
[2025-01-14T16:57:08.786-0500] {processor.py:186} INFO - Started process (PID=5432) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:57:08.787-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:57:08.788-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:57:08.788-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:57:08.822-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:57:08.822-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:57:08.823-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:57:08.822-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:57:08.823-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:57:08.970-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.189 seconds
[2025-01-14T16:59:47.225-0500] {processor.py:186} INFO - Started process (PID=7287) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:59:47.227-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T16:59:47.228-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:59:47.228-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:59:47.277-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:59:47.276-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T16:59:47.277-0500] {logging_mixin.py:190} INFO - [2025-01-14T16:59:47.277-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T16:59:47.277-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T16:59:47.480-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.262 seconds
[2025-01-14T17:02:54.609-0500] {processor.py:186} INFO - Started process (PID=9535) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:02:54.610-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:02:54.612-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:02:54.611-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:02:54.651-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:02:54.651-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:02:54.652-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:02:54.652-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:02:54.652-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:02:54.828-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.225 seconds
[2025-01-14T17:05:42.593-0500] {processor.py:186} INFO - Started process (PID=11476) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:05:42.595-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:05:42.596-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:05:42.596-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:05:42.641-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:05:42.640-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:05:42.641-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:05:42.641-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:05:42.642-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:05:42.826-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.238 seconds
[2025-01-14T17:08:25.814-0500] {processor.py:186} INFO - Started process (PID=13348) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:08:25.816-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:08:25.817-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:08:25.817-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:08:25.851-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:08:25.851-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:08:25.852-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:08:25.851-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:08:25.852-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:08:26.002-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.192 seconds
[2025-01-14T17:11:10.711-0500] {processor.py:186} INFO - Started process (PID=15253) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:11:10.713-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:11:10.714-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:11:10.714-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:11:10.753-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:11:10.752-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:11:10.753-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:11:10.753-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:11:10.753-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:11:10.913-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.206 seconds
[2025-01-14T17:13:37.087-0500] {processor.py:186} INFO - Started process (PID=16905) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:13:37.089-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:13:37.090-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:13:37.090-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:13:37.127-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:13:37.126-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:13:37.127-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:13:37.127-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:13:37.127-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:13:37.328-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.245 seconds
[2025-01-14T17:15:54.851-0500] {processor.py:186} INFO - Started process (PID=18434) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:15:54.852-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:15:54.853-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:15:54.853-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:15:54.889-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:15:54.888-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:15:54.889-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:15:54.889-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:15:54.889-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:15:55.042-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.195 seconds
[2025-01-14T17:18:14.995-0500] {processor.py:186} INFO - Started process (PID=20055) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:18:14.997-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:18:14.998-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:18:14.998-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:18:15.039-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:18:15.039-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:18:15.040-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:18:15.040-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:18:15.040-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:18:15.195-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.205 seconds
[2025-01-14T17:22:53.674-0500] {processor.py:186} INFO - Started process (PID=23231) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:22:53.676-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:22:53.677-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:22:53.677-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:22:53.710-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:22:53.710-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:22:53.711-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:22:53.710-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:22:53.711-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:22:53.867-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.197 seconds
[2025-01-14T17:25:20.343-0500] {processor.py:186} INFO - Started process (PID=24869) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:25:20.344-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:25:20.345-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:25:20.345-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:25:20.381-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:25:20.380-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:25:20.381-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:25:20.381-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:25:20.382-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:25:20.537-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.199 seconds
[2025-01-14T17:27:39.990-0500] {processor.py:186} INFO - Started process (PID=26510) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:27:39.991-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:27:39.992-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:27:39.992-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:27:40.024-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:27:40.024-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:27:40.024-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:27:40.024-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:27:40.024-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:27:40.180-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.195 seconds
[2025-01-14T17:30:02.797-0500] {processor.py:186} INFO - Started process (PID=28157) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:30:02.799-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:30:02.800-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:30:02.800-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:30:02.838-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:30:02.837-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:30:02.838-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:30:02.838-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:30:02.838-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:30:02.996-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.203 seconds
[2025-01-14T17:32:22.192-0500] {processor.py:186} INFO - Started process (PID=29686) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:32:22.193-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:32:22.195-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:32:22.195-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:32:22.229-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:32:22.229-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:32:22.229-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:32:22.229-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:32:22.229-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:32:22.377-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.189 seconds
[2025-01-14T17:34:43.232-0500] {processor.py:186} INFO - Started process (PID=31323) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:34:43.234-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:34:43.235-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:34:43.235-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:34:43.267-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:34:43.266-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:34:43.267-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:34:43.267-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:34:43.267-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:34:43.410-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.182 seconds
[2025-01-14T17:36:53.695-0500] {processor.py:186} INFO - Started process (PID=32881) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:36:53.696-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:36:53.697-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:36:53.697-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:36:53.737-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:36:53.736-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:36:53.737-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:36:53.737-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:36:53.737-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:36:53.888-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.198 seconds
[2025-01-14T17:41:31.397-0500] {processor.py:186} INFO - Started process (PID=36032) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:41:31.405-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:41:31.425-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:41:31.424-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:41:31.464-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:41:31.463-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:41:31.464-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:41:31.464-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:41:31.464-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:41:31.631-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.239 seconds
[2025-01-14T17:45:55.740-0500] {processor.py:186} INFO - Started process (PID=39141) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:45:55.742-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:45:55.744-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:45:55.743-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:45:55.777-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:45:55.776-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:45:55.777-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:45:55.777-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:45:55.777-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:45:55.936-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.200 seconds
[2025-01-14T17:50:27.142-0500] {processor.py:186} INFO - Started process (PID=42294) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:50:27.143-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:50:27.144-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:50:27.144-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:50:27.179-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:50:27.179-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:50:27.180-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:50:27.180-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:50:27.180-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:50:27.346-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.208 seconds
[2025-01-14T17:52:43.076-0500] {processor.py:186} INFO - Started process (PID=43828) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:52:43.078-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:52:43.080-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:52:43.079-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:52:43.114-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:52:43.114-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:52:43.115-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:52:43.114-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:52:43.115-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:52:43.280-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.208 seconds
[2025-01-14T17:54:57.832-0500] {processor.py:186} INFO - Started process (PID=45408) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:54:57.834-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:54:57.835-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:54:57.835-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:54:57.872-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:54:57.872-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:54:57.873-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:54:57.872-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:54:57.873-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:54:58.027-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.200 seconds
[2025-01-14T17:57:19.187-0500] {processor.py:186} INFO - Started process (PID=47072) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:57:19.189-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:57:19.190-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:57:19.190-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:57:19.232-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:57:19.231-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:57:19.232-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:57:19.232-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:57:19.233-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:57:19.392-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.210 seconds
[2025-01-14T17:59:34.684-0500] {processor.py:186} INFO - Started process (PID=48648) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:59:34.686-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T17:59:34.687-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:59:34.687-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:59:34.718-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:59:34.718-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T17:59:34.718-0500] {logging_mixin.py:190} INFO - [2025-01-14T17:59:34.718-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T17:59:34.718-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T17:59:34.863-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.183 seconds
[2025-01-14T18:01:57.052-0500] {processor.py:186} INFO - Started process (PID=50273) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:01:57.053-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T18:01:57.054-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:01:57.054-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:01:57.087-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:01:57.087-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T18:01:57.088-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:01:57.087-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T18:01:57.088-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:01:57.235-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.187 seconds
[2025-01-14T18:04:17.200-0500] {processor.py:186} INFO - Started process (PID=51840) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:04:17.202-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T18:04:17.203-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:04:17.203-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:04:17.238-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:04:17.238-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T18:04:17.239-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:04:17.239-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T18:04:17.239-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:04:17.391-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.195 seconds
[2025-01-14T18:06:34.775-0500] {processor.py:186} INFO - Started process (PID=53479) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:06:34.776-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T18:06:34.778-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:06:34.777-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:06:34.811-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:06:34.811-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T18:06:34.812-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:06:34.812-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T18:06:34.812-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:06:34.961-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.190 seconds
[2025-01-14T18:08:48.449-0500] {processor.py:186} INFO - Started process (PID=55005) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:08:48.451-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T18:08:48.452-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:08:48.452-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:08:48.484-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:08:48.484-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T18:08:48.484-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:08:48.484-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T18:08:48.485-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:08:48.630-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.186 seconds
[2025-01-14T18:11:03.837-0500] {processor.py:186} INFO - Started process (PID=56525) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:11:03.838-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T18:11:03.839-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:11:03.839-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:11:03.869-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:11:03.869-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T18:11:03.870-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:11:03.870-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T18:11:03.870-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:11:04.016-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.183 seconds
[2025-01-14T18:15:31.743-0500] {processor.py:186} INFO - Started process (PID=59564) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:15:31.745-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T18:15:31.746-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:15:31.746-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:15:31.780-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:15:31.779-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T18:15:31.780-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:15:31.780-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T18:15:31.780-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:15:31.925-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.186 seconds
[2025-01-14T18:17:48.266-0500] {processor.py:186} INFO - Started process (PID=61109) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:17:48.267-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T18:17:48.268-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:17:48.268-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:17:48.301-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:17:48.300-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T18:17:48.301-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:17:48.301-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T18:17:48.301-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:17:48.448-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.185 seconds
[2025-01-14T18:22:10.537-0500] {processor.py:186} INFO - Started process (PID=64176) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:22:10.538-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T18:22:10.539-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:22:10.539-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:22:10.572-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:22:10.571-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T18:22:10.572-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:22:10.572-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T18:22:10.572-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:22:10.709-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.176 seconds
[2025-01-14T18:46:01.727-0500] {processor.py:186} INFO - Started process (PID=66209) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:46:01.729-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T18:46:01.730-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:46:01.730-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:46:01.767-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:46:01.766-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T18:46:01.767-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:46:01.767-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T18:46:01.768-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:46:01.928-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.206 seconds
[2025-01-14T18:48:34.527-0500] {processor.py:186} INFO - Started process (PID=68042) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:48:34.530-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T18:48:34.531-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:48:34.531-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:48:34.568-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:48:34.568-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T18:48:34.569-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:48:34.569-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T18:48:34.569-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:48:34.737-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.214 seconds
[2025-01-14T18:50:51.511-0500] {processor.py:186} INFO - Started process (PID=69566) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:50:51.512-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T18:50:51.513-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:50:51.513-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:50:51.552-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:50:51.551-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T18:50:51.552-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:50:51.552-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T18:50:51.552-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:50:51.731-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.225 seconds
[2025-01-14T18:55:27.553-0500] {processor.py:186} INFO - Started process (PID=72706) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:55:27.555-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T18:55:27.556-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:55:27.556-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:55:27.595-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:55:27.594-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T18:55:27.595-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:55:27.595-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T18:55:27.595-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:55:27.751-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.202 seconds
[2025-01-14T18:57:45.017-0500] {processor.py:186} INFO - Started process (PID=74370) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:57:45.019-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T18:57:45.020-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:57:45.020-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:57:45.059-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:57:45.058-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T18:57:45.059-0500] {logging_mixin.py:190} INFO - [2025-01-14T18:57:45.059-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T18:57:45.059-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T18:57:45.221-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.208 seconds
