[2025-01-14T19:00:13.208-0500] {processor.py:186} INFO - Started process (PID=76068) to work on /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T19:00:13.209-0500] {processor.py:914} INFO - Processing file /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-14T19:00:13.211-0500] {logging_mixin.py:190} INFO - [2025-01-14T19:00:13.211-0500] {dagbag.py:588} INFO - Filling up the DagBag from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T19:00:13.251-0500] {logging_mixin.py:190} INFO - [2025-01-14T19:00:13.251-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-14T19:00:13.252-0500] {logging_mixin.py:190} INFO - [2025-01-14T19:00:13.252-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-14T19:00:13.252-0500] {processor.py:927} WARNING - No viable dags retrieved from /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-14T19:00:13.428-0500] {processor.py:208} INFO - Processing /usr/local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.224 seconds
