[2025-01-13T18:12:54.558-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-13T18:12:54.572-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2025-01-13T23:06:07.933496+00:00 [queued]>
[2025-01-13T18:12:54.579-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2025-01-13T23:06:07.933496+00:00 [queued]>
[2025-01-13T18:12:54.580-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-01-13T18:12:54.590-0500] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): inaccurate> on 2025-01-13 23:06:07.933496+00:00
[2025-01-13T18:12:54.596-0500] {standard_task_runner.py:72} INFO - Started process 11697 to run task
[2025-01-13T18:12:54.604-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2025-01-13T23:06:07.933496+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/tutorial_taskflow_api.py', '--cfg-path', '/var/folders/ll/2bfcn_d54ks002mx2dw82c2m0000gn/T/tmpzscn2cw1']
[2025-01-13T18:12:54.608-0500] {standard_task_runner.py:105} INFO - Job 27: Subtask inaccurate
[2025-01-13T18:12:54.657-0500] {task_command.py:467} INFO - Running <TaskInstance: my_dag.inaccurate manual__2025-01-13T23:06:07.933496+00:00 [running]> on host macbook-pro-2.local
[2025-01-13T18:12:54.720-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T23:06:07.933496+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T23:06:07.933496+00:00'
[2025-01-13T18:12:54.723-0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-13T18:12:54.724-0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-13T18:12:54.725-0500] {logging_mixin.py:190} INFO - Current task name:inaccurate state:running start_date:2025-01-13 23:12:54.572986+00:00
[2025-01-13T18:12:54.725-0500] {logging_mixin.py:190} INFO - Dag name:my_dag and current dag run status:running
[2025-01-13T18:12:54.726-0500] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-13T18:12:54.728-0500] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/ll/2bfcn_d54ks002mx2dw82c2m0000gn/T
[2025-01-13T18:12:54.729-0500] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2025-01-13T18:12:54.737-0500] {subprocess.py:99} INFO - Output:
[2025-01-13T18:12:54.747-0500] {subprocess.py:106} INFO - inaccurate
[2025-01-13T18:12:54.748-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-13T18:12:54.765-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-13T18:12:54.767-0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, run_id=manual__2025-01-13T23:06:07.933496+00:00, execution_date=20250113T230607, start_date=20250113T231254, end_date=20250113T231254
[2025-01-13T18:12:54.774-0500] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-13T18:12:54.775-0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-13T18:12:54.776-0500] {logging_mixin.py:190} INFO - Dag name:my_dag queued_at:2025-01-13 23:06:07.955311+00:00
[2025-01-13T18:12:54.777-0500] {logging_mixin.py:190} INFO - Task hostname:macbook-pro-2.local operator:BashOperator
[2025-01-13T18:12:54.819-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-13T18:12:54.836-0500] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-13T18:12:54.837-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
