[2025-01-14T15:56:39.595-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-14T15:56:39.608-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2025-01-14T20:56:17.196394+00:00 [queued]>
[2025-01-14T15:56:39.615-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2025-01-14T20:56:17.196394+00:00 [queued]>
[2025-01-14T15:56:39.615-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-01-14T15:56:39.626-0500] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): inaccurate> on 2025-01-14 20:56:17.196394+00:00
[2025-01-14T15:56:39.633-0500] {standard_task_runner.py:72} INFO - Started process 63264 to run task
[2025-01-14T15:56:39.645-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2025-01-14T20:56:17.196394+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/tutorial_taskflow_api.py', '--cfg-path', '/var/folders/ll/2bfcn_d54ks002mx2dw82c2m0000gn/T/tmpjawt4kw_']
[2025-01-14T15:56:39.648-0500] {standard_task_runner.py:105} INFO - Job 67: Subtask inaccurate
[2025-01-14T15:56:39.700-0500] {task_command.py:467} INFO - Running <TaskInstance: my_dag.inaccurate manual__2025-01-14T20:56:17.196394+00:00 [running]> on host macbook-pro-2.local
[2025-01-14T15:56:39.766-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T20:56:17.196394+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-14T20:56:17.196394+00:00'
[2025-01-14T15:56:39.768-0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-14T15:56:39.769-0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-14T15:56:39.770-0500] {logging_mixin.py:190} INFO - Current task name:inaccurate state:running start_date:2025-01-14 20:56:39.608950+00:00
[2025-01-14T15:56:39.770-0500] {logging_mixin.py:190} INFO - Dag name:my_dag and current dag run status:running
[2025-01-14T15:56:39.771-0500] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-14T15:56:39.773-0500] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/ll/2bfcn_d54ks002mx2dw82c2m0000gn/T
[2025-01-14T15:56:39.774-0500] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2025-01-14T15:56:39.783-0500] {subprocess.py:99} INFO - Output:
[2025-01-14T15:56:39.788-0500] {subprocess.py:106} INFO - inaccurate
[2025-01-14T15:56:39.790-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-14T15:56:39.809-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-14T15:56:39.811-0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, run_id=manual__2025-01-14T20:56:17.196394+00:00, execution_date=20250114T205617, start_date=20250114T205639, end_date=20250114T205639
[2025-01-14T15:56:39.819-0500] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-14T15:56:39.820-0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-14T15:56:39.821-0500] {logging_mixin.py:190} INFO - Dag name:my_dag queued_at:2025-01-14 20:56:17.211017+00:00
[2025-01-14T15:56:39.821-0500] {logging_mixin.py:190} INFO - Task hostname:macbook-pro-2.local operator:BashOperator
[2025-01-14T15:56:39.858-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-14T15:56:39.875-0500] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-14T15:56:39.876-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
